from typing import Dict, List


class DependencyResolver:
    """
    Resolves task dependencies and determines
    the correct execution order.
    """

    def resolve(
        self,
        tasks: List[Dict],
    ) -> List[Dict]:
        """
        Resolve dependencies between tasks.

        Currently this performs a simple ordering
        based on the task order generated by the planner.

        Future versions may support:
        - Parallel execution
        - DAG scheduling
        - Circular dependency detection
        - Dynamic dependency injection
        """

        ordered_tasks = sorted(
            tasks,
            key=lambda task: task.get("order", 0),
        )

        previous_task_id = None

        for task in ordered_tasks:

            task["depends_on"] = previous_task_id

            previous_task_id = task["task_id"]

        return ordered_tasks


dependency_resolver = DependencyResolver()